build:
  environment:
    php:
      version: 7.4.1
  tests:
    override:
      -
        command: 'vendor/bin/phpunit test/phpunit --coverage-clover coverage --whitelist src'
        coverage:
          file: 'coverage'
          format: 'php-clover'

checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - test/*
    - vendor/*